version: '3'

services:
  users_service:
    image: freddylor/microservice_studens-users_service-1:latest  # Cambiado a imagen específica
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - my-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: userdb
      MYSQL_USER: adminroot
      MYSQL_PASSWORD: rootroot1
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql    
    ports:
      - "5001:3306"
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8086:80"
    networks:
      - my-network

  gateway_service:
    image: freddylor/microservice_studens-gateway_service-1:tagname  # Cambiado a imagen específica y etiqueta
    ports:
      - "5002:5002"
    depends_on:
      - users_service
    networks:
      - my-network

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "8086:80"
  #   depends_on:
  #     - gateway_service
  #   networks:
  #     - my-network

networks:
  my-network:
    driver: bridge
