version: '3'

services:
  users_service:
    build:
      context: ./users_service
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - my-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: userdb
      MYSQL_USER: adminroot
      MYSQL_PASSWORD: rootroot1
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql    
    ports:
      - "5001:5001"
    networks:
      - my-network

  gateway_service:
    build:
      context: ./gateway_service
    ports:
      - "5002:5002"
    depends_on:
      - users_service
    networks:
      - my-network

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "8086:80"
  #   depends_on:
  #     - gateway_service
  #   networks:
  #     - my-network

networks:
  my-network:

  # Agrega aquí la configuración para tu frontend Vue si también se ejecuta en contenedores
